//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.3053.
// 
namespace TrainCheck.TrainService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DataServicesSoap", Namespace="http://tempuri.org/")]
    public partial class DataServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public DataServices() {
            this.Url = "http://192.168.229.128/TrainCheckWeb/DataServices.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UserList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable UserList() {
            object[] results = this.Invoke("UserList", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUserList(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UserList", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndUserList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SpecsList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable SpecsList() {
            object[] results = this.Invoke("SpecsList", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSpecsList(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SpecsList", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndSpecsList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SpecsItemsList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable SpecsItemsList() {
            object[] results = this.Invoke("SpecsItemsList", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSpecsItemsList(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SpecsItemsList", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndSpecsItemsList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UploadJob", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UploadJob(string jobdate, int userid, string begintime, string endtime, string ipaddress, int needcheckposition, int checkposition, int passposition, string childList) {
            object[] results = this.Invoke("UploadJob", new object[] {
                        jobdate,
                        userid,
                        begintime,
                        endtime,
                        ipaddress,
                        needcheckposition,
                        checkposition,
                        passposition,
                        childList});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUploadJob(string jobdate, int userid, string begintime, string endtime, string ipaddress, int needcheckposition, int checkposition, int passposition, string childList, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UploadJob", new object[] {
                        jobdate,
                        userid,
                        begintime,
                        endtime,
                        ipaddress,
                        needcheckposition,
                        checkposition,
                        passposition,
                        childList}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndUploadJob(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
    }
}
